# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveStreamDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveStreamDemo
    pod 'KurentoToolbox', :path => "/My\ Data/Souce/Framework/KurentoToolbox"
    pod 'Starscream'
    
  target 'LiveStreamDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
