# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveStreamDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveStreamDemo
    pod 'Starscream'
    pod 'KurentoToolbox'
    
  target 'LiveStreamDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
