# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KurentoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KurentoToolbox', :path => "/My\ Data/Souce/Framework/WebRTCKurento/KurentoToolbox"
  pod 'Starscream'

  target 'KurentoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KurentoDemoUITests' do
    # Pods for testing
  end

end
